" Filetype plugin to detect filetypes and allow specific settings.
filetype indent plugin on

" Turn on Syntax Highlighting.
syntax on

" Allow backspace to also work as expected in other text-based programs.
set backspace=indent,eol,start

" Allow for new files to be opened without forcing a write.
set hidden

" Allow for only the user-specified runtimepath to be used.
let $RTP=split(&runtimepath, ",")[0]

" Quick environment variable to get to this .vimrc file.
let $RC="$HOME/.vim/vimrc"

" Old settings
"" set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
"" au filetype gitcommit set textwidth=72
