alias ls="ls --color=always -h"
alias grep="grep --color=always"
alias gs="git status"
alias gcm="git commit"
alias gpo='git push -u origin $(git rev-parse --abbrev-ref HEAD)'
alias gp="git pull"
alias gc="git checkout"
alias gcb="git checkout -b"
alias gcdf="git clean -f -d"
alias grb="git rebase"
alias ga="git add --all"
alias gcma="git add --all && git commit"
alias gl="git log"
alias gd="git diff"
alias gds="git diff --staged"
